var arr1 = ["Punit", "Sakshi", "Atul", "Monika"];
var newArray = arr1.push("Raman");
console.log(newArray);
console.log(arr1);
var removeArray = arr1.pop();
console.log(removeArray);
console.log(arr1);
var anotherArray = arr1.unshift("Raman");
console.log(anotherArray);
console.log(arr1);
var removeFirst = arr1.shift();
console.log(removeFirst);
console.log(arr1);
